name: Frist Workflow

on:
  push:
    branches:
      -main

jobs:
  example-job:
    runs-on: windows-latest

    steps:
      - name: print a welcome message
        run: echo "Welcome to our frist GitHub Actions Workflow !"
      
    
    

    
